version: 1.0.0.{build}
image: Visual Studio 2022

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- ps: dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.RDP.csproj

after_build:
- ps: Compress-Archive -Path .\bin\Release\win-x64\* -DestinationPath "Flow.Launcher.Plugin.RDP.zip"

artifacts:
    - path: 'Flow.Launcher.Plugin.RDP.zip'
   
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: P73qEX1e76HuKlPIqoXg9+LsYEwOYt5mwEtKWJdKBIH9Gfj+y2q2MKwc+ygUkJSf
  repository: MBeggiato/Flow.Launcher.Plugin.RDP