# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.RDP.csproj
    - name: Zip
      run: Compress-Archive -Path .\bin\Release\win-x64\* -DestinationPath "Flow.Launcher.Plugin.RDP.zip"
    - name: Version Increment
      uses: reecetech/version-increment@2023.9.3
      with:
          scheme: semver
          increment: patch
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.7.0
      with:
          file: Flow.Launcher.Plugin.RDP.zip
          asset_name: Flow.Launcher.Plugin.RDP.${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          overwrite: true
            
            
